Include move_amount.py
STealthy-and-haSTy/SublimeScraps pull request #6
Opened 2017-09-23 05:09 UTC by OdatNurd

Include the move_amount command that was originally written on the
Sublime forum and just recently cross posted to Stack Overflow. This
implements a drop in replacement for the move command that allows you
to specify how many times the action should happen.

2017-09-23 05:43 UTC, keith-hall requested changes
couple of small documentation/comment related improvements

2017-09-23 05:43 UTC, keith-hall commented on plugins/README.md
> +   movement happens. This can be handy for certain kinda of navigation or in
I think there's a typo here - `kinda of` should be `kinds of`

2017-09-23 05:43 UTC, keith-hall commented on plugins/move_amount.py
> +#     https://forum.sublimetext.com/t/command-to-move-by-several-lines/28508
related reading links are the same, should there be two different links or just the one?

2017-09-23 23:09 UTC, OdatNurd commented
Typo and link fixed. I also enabled a project setting to ensure newlines at the ends of files. We may want to run a change to re-save all files to get them into a good state.

2017-09-24 04:42 UTC, keith-hall approved these changes

2017-09-24 04:42 UTC, merged